- lib/compile.js
Okay, a few things going on here:
- explicit null rather than undefined for skipping tokens in a rule
- which allows us to then pull apart the if/else ladder into a set of decoupled short-circuiting ifs
- which then allows us to easily re-order the checks, and expand them in future changes
- use said flexibility to do the inexpensive "atomic" checks first
> Clearer edge cases

- package.json
- test/launch.js
- test/whitespace.ne
Here are some tests using Mocha & Chai, in a separate branch so they can be merge without worrying about changes to the runtime. Currently the test "nullable whitespace bug" fails (fix in PR #86).
> Mocha tests

- package.json
- test/launch.js
fix 'npm test' error ( test on windows 10 / node v5.8.0 & Linux 4.2.0-c9 / node v4.4.0 ) 
1.on windows you have to say 'node XX.js' instead of only 'XX.js'
2.to make test 'should build for CoffeeScript' pass, I add coffee script as dev dependency (I don't think I everybody install coffee script on their machine in 2016)
> fix npm test error on windows

- lib/nearley.js
"findLeo" seems to take 80% of the runtime for a JSON grammar example.
* Avoids iterating over the row twice.
* Avoids the creation of the anonymous function in the map/filter
high order functions.
Results in Chrome (V8).
X3 speed in JSON Grammar + Tokenizer.
x2 speed in JSON Grammar without Tokenizer.
> Performance optimization:

- bin/nearley-railroad.js
- package.json
This commit stops `npm install nearley` failing if for whatever reason, `railroad-diagrams` is not installed. (`nearley-railroad` shall throw an error if `railroad-diagrams` is not installed when it is run.)
This resolves #102 and relies on [package.json optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies).
> railroad-diagrams as an optionalDependency

- README.md
Any time you're describing a language for describing a language, it can get confusing.  I found this line in the `README` confusing, because I didn't know whether it meant "You can add a nearley file, `#` starts a comment" or "This grammar defines a language that ignores comments beginning with `#`.  There's no use of `#` in the example that clarifies it.  Based on http://nearley.js.org/www/railroad-demo.html, I'm sure you meant the former, so how about describe it with a second example?
> Which language is the comment comment about?

- README.md
I know `|` is used by Unix shells to indicate a pipe, but it's also a standard symbol for a disjunction in many programming languages (bitwise _or_, or two for logical _or_), and that's how you're using it in nearley.  This tripped me up when reading this, the same way as it would if you'd said
> To divide two numbers, separate them with a pathname delimiter (`/`)
or if you'd called the comment character a "number sign" or "hash sign" or a "sharp sign", all of which are good names for the octothorpe character in other contexts.
> Vertical bar

- lib/nearley.js
function did not bind to enclosing scope but still used `this` which was undefined
> fixing undefined `this`

- bin/nearley-railroad.js
Improving the HTML document produced by `nearley-railroad`. The document now specifies a UTF-8 charset allowing for unicode characters within railroad diagrams to be rendered correctly.
> Improve HTML output of railroad, including a meta-tag for UTF-8

- lib/nearley.js
Line 73 causes the following error in strict mode: `In strict mode, function declarations cannot be nested inside a statement or block. They may only appear at the top level or directly inside a function body.`
This is simply fixed by assigning the function to a variable.
Would be good to get this fix in as we are running our entire app in strict mode, and since pulling in nearly, have lost some browser compatibility due to this error.
> Fix for strict mode

- bin/nearley-test.js
> nearley-test: Provide `type: string` on --input option

- examples/tosh.ne
- test/launch.js
This is an example grammar (and associated test!) based on the grammar used for **tosh: [tosh.tjvr.org](https://tosh.tjvr.org/)**.
You might wish to compare this nearley-flavoured example with [the tosh grammar reference](https://tosh.tjvr.org/help/grammar/).
_Context: tosh currently uses a homegrown Earley parser, inspired by Nearley. Hopefully one day I can switch, once performance for large grammars is fast enough to support syntax highlighting a line (and running CFG completion!) after each keypresss. :)_
> Add tosh example

- package.json
- test/_shared.js
- test/benchmark.js
- test/launch.js
Today's patch: adding a lil benchmark suite.
Yes, benchmarking nearley's JSON example against a native JSON parser is
hilarious and stupid. But it demonstrates that the benchmarks work (-:
I've also refactored the existing tests to invoke nearleyc directly, rather than through a subprocess. This makes `npm test` a fair bit faster (4s -> 2s over here).
@hardmath123 What do you think? :-)
---
$ npm run benchmark
> Benchmark suite

- lib/compile.js
- lib/generate.js
When testing #171 I found I was running out of memory when parsing a large JSON sample (~1kB), using the example scannerless JSON parser in the repo.
I realised that we're expanding EBNF rules like
```
string -> "\"" validChar:* "\""
```
into
```
string$ebnf$1 -> 
| validChar string$ebnf$1
```
Since Earley loves left-recursion, I think it would be better to expand these left-recursively instead! In particular, I *think* this avoids some weird n^2 behaviour when parsing long strings.
Anyway, even on master this patch appears to speed up a 1k JSON sample by ~3x, so this seems worthwhile :-)
@hardmath123 What do you think?
> Left-recursive EBNF expansion

- README.md
- bin/nearley-test.js
- lib/nearley.js
- test/_shared.js
- test/benchmark.js
- test/launch.js
First, we allow Parser to accept a Grammar directly. This is the preferred way, since it avoids constructing the Grammar every time we want to parse something (which has a cost O(n) in the size of the grammar). I've modified the benchmarks to cache the Grammar object, so there should be a minor speed bump there (should be more for larger grammars I guess?).
To make the tests easier to write, I added `Grammar.fromCompiled()`. There are thus three ways to get a grammar:
Grammar(rules, start) // note: list of Rule objects
Grammar.fromCompiled({ParserRules,ParserStart})
Grammar.fromCompiled(ParserRules, ParserStart)
This is also used for backwards-compatibility in the Parser constructor, so you can still construct a Parser the old way (even though caching your Grammar is preferred).
Then, we …
> Add history option & refactor Grammar construction

- examples/tosh.ne
- lib/nearley.js
- test/launch.js
First off, we require calling finish() before reading `results`. This is a deliberate **API change**.
Currently, we "incrementally keep track of results". This means feeding the input in multiple chunks has a performance penalty.
I've patched our Stream implementation, so users of that API won't even notice this change!
Everyone else will have to drop in a `p.finish()` line before they read `p.results`.
Then, I added rewind(index), which requires the `keepHistory` option. It resets the parser state to the state after seeing that token. So if you feed it 10 tokens, rewind(10) has no effect. [rewind(11) is an error; you can't rewind forwards!]
Note that this is *not a reset* method. If you want to reset a parser, throw it away and initialise a new one. Assuming you're using `Grammar` …
> Add rewind()

- lib/compile.js
- lib/generate.js
- lib/nearley.js
This PR resolves #196 
The comments I've removed were fooling SystemJS into thinking that nearley was an AMD module.
> Fix: Allow SystemJS to correctly infer module type

- builtin/string.ne
Original did not properly matching code like `'foo''bar'`.
> Fixed sstrchar definition

- lib/compile.js
- lib/generate.js
- package.json
- test/launch.js
- test/tsconfig.json
- test/typescript-test.ne
Mega-PR with all the fixes for TypeScript.
- Improve and export interfaces from the generated TS. Closes #233, #234.
- Add `arrpush` built-in postprocessor as in other generators. Closes #223.
- Declare custom tokens in the generated TS to avoid errors when compiling to JS. Closes #241.
The first commit (055d79bc213102173118f67b1078c0f032066c21) is a squashed and consistently formatted version of #234. I double-checked, it's equivalent to that PR, nothing was lost. That PR looks larger because of the formatting changes.
> Fix TypeScript postprocessor: improve and export types

- how-to-grammar-good.md
- lib/nearley.js
I pulled [the awesome!] Nearley into a personal project via Browserify and found that when Browserify added 'use strict', Nearley crashed in a `where` clause. This change fixes it (and I tweaked the docs as well. :) )
> Strict mode compatibility fix

- README.md
I wrote a small gulp plugin wrapper around the existing `nearly-loader` plugin, and thought it might be useful to others as well. I tried to match the format of the other tooling links in the README.
> Adds link to nearley-gulp in README

- package-lock.json
- package.json
- test/benchmark.js
This halves the amount of code in `benchmarks.js`, makes it easier to compare benchmarks across different libraries if we want to do that, and makes it easier to add new benchmarks. :-)
> Refactor benchmarks using benchr

- docs/accessing-parse-table.html
- docs/custom-tokens-and-lexers.html
- docs/glossary.html
- docs/how-to-grammar-good.html
- docs/index.html
- docs/layouts/template.html
- docs/make.js
- docs/package-lock.json
- docs/package.json
- docs/tooling.html
- docs/using-in-frontend.html
- www/main.css
This avoids FOIT in favour of FOUT: that is, show a fallback font while the webfont (Roboto) is loading. This means the content is readable in half the time, on a slow connection. (This is how `@font-face` used to work, before browsers changed their behaviour.)
This also inlines the CSS, to avoid an additional blocking request before the content can be rendered.
Before (>7s to content):
---
After: (<3s to content):
> Optimise docs site

- package.json
* This brings the package size from 1.6M -> 432K.
* Reducing the package size is nice; it means our users have less to download.
* README.md & LICENSE.txt will be included automatically.
* I'd rather not include `examples/`, but there's a small chance someone will
depend on it?
People on rubbish connections (as I sometimes am!) should appreciate this. :-)
> Exclude tests & docs from NPM package

- lib/generate.js
This is just a small change to make the generated grammar file a little more readable, especially for TypeScript users.
> Make generation output more readable

- builtin/postprocessors.ne
- lib/generate.js
- package-lock.json
- package.json
With the [release](https://github.com/Microsoft/TypeScript/releases/tag/v2.6.1) of TypeScript 2.6.1, we now have the option to [suppress errors in .ts files using '// @ts-ignore' comments](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#suppress-errors-in-ts-files-using--ts-ignore-comments).
Fixes #322
> Bypass TS6133 error by allowing function declarations that are unused

- bin/nearley-railroad.js
If you use e.g. moo as a lexer, terminals are shown as "[Unimplemented]" in the railroad diagram. This adds them as terminals with the token name
> Added tokens from lexer as terminals in railroad diagram

- bin/nearley-unparse.js
- lib/unparse.js
I basically moved the generation functions from `nearley-unparse` into the core `nearley` module as a `Generator` class that gets exported along with the other core types.
Now `nearley-unparse` simply acts as a script wrapper around the `Generator` functionality. 
This exposes the generation functionality to arbitrary user code.
I tried to fit the existing code style, and `npm run test` doesn't report any (new) failures.
If merged, this would resolve the concern I raised in issue #334
> Refactor nearley-unparse generation code into core

- docs/md/grammar.md
In the `@builtin` section, it says to look at the builtin/ directory on github, but it doesn't provide a link.
> A link to the builtin directory on github in the grammar docs

- package.json
This PR updates the `randexp` dependency to use the fixed version `0.4.6`, since the latest `0.4.7` has a [breaking change for git-less environments](https://github.com/fent/randexp.js/issues/46) when installing the package.
Issue: https://github.com/kach/nearley/issues/346
> Fix #346: randexp dependency

- .travis.yml
- docs/package-lock.json
This adds Travis checks that, for every commit and pull request:
* Checks the tests pass
* Checks the benchmarks don’t throw errors
* Builds the docs
* Checks the working state is clean (ie. the docs are fresh!)
Travis is quick to setup, and having a pass/fail status on every PR gives an extra little reassurance to us maintainers. Please could you set this up @Hardmath123? You just need to log in to <http://travis-ci.org> and enable Travis for hardmath123/nearley. :-)
(The build currently fails, so we can check Travis is working properly! I’ll fix that once this is merged :-))
> Add Travis checks

- lib/lint.js
- package.json
@kach You added a lint warning in c82a2b9 to direct TypeScript users to #287.
This broke the unit tests:
```
1) bin/nearleyc builds for TypeScript:
Error: Expected 'WARN\tThe interface for the TypeScript preprocessor changed briefly in nearley 2.10 and 2.11. See https://github.com/Hardmath123/nearley/pull/287 if you encounter issues importing your grammar into TS.\n' to be ''
at assert (node_modules/expect/lib/assert.js:29:9)
at Expectation.toBe (node_modules/expect/lib/Expectation.js:66:28)
at Context.<anonymous> (test/nearleyc.test.js:65:24)
```
We either need to amend the unit test, or remove the lint warning. Since some time has passed since the warning as added, this PR removes it.
---
*Aside:* I thought we'd enabled Travis CI, which would warn us about this sort of thing; but [it …
> Remove TypeScript warning

- docs/md/tokenizers.md
- docs/tokenizers.html
- lib/nearley.js
- test/bootstrap.test.js
Moo recently introduced a distinction between `text` (the original match) and `value`. However, Nearley literals are still matched against `value`. Moo can extract a part of a token into the `value`. (We used to do this with capture groups; now we do this with a `value` function.) For example, the value of a string token excludes the quotes.
There is a really nasty gotcha that's been bugging me for a while: if you have a literal in your grammar to match (, it will *also* match the string "("!
My proposed fix is to modify Nearley to match literals instead against `tok.text`, if present. Since this is a bugfix, and backwards compatible (we fall back to `tok.value`), this won't violate semver. :)
Related: #359 and some others
> Token value fix

- docs/md/tooling.md
- docs/tooling.html
I've written a parcel plugin and a jest transform for nearley grammars, both inspired by `nearley-loader`
I've added links to those on the tooling page.
> Add tooling links to parcel-plugin-nearley and jest-transform-nearley

- lib/nearley-language-bootstrapped.js
- lib/nearley-language-bootstrapped.ne
- lib/nearley.js
- test/bootstrap.test.js
Fixes #457.
```
$ npm run benchmark
> nearley@2.17.0 benchmark /home/hzhang/Code/nearley
> benchr test/benchmark.js
• test/benchmark.js:
• calculator: parse.
✔  nearley  12,077.18  ops/sec  ±2.77%  (82 runs)
• json: parse sample1k.
✔  nearley  111.83  ops/sec  ±0.89%  (72 runs)
• tosh: parse.
✔  nearley  2,070.69  ops/sec  ±1.14%  (91 runs)
```
```
$ npm run benchmark
> nearley@2.17.0 benchmark /home/hzhang/Code/nearley
> benchr test/benchmark.js
• test/benchmark.js:
• calculator: parse.
✔  nearley  13,366.74  ops/sec  ±0.42%  (95 runs)
• json: parse sample1k.
✔  nearley  112.56  ops/sec  ±0.88%  (78 runs)
• tosh: parse.
✔  nearley  2,088.54  ops/sec  ±1.94%  (87 runs)
```
```
$ npm run test
> nearley@2.17.0 test /home/hzhang/Code/nearley
> mocha test/*.test.js
bootstrapped lexer
✓ lexes …
```
> Remove ES6+ code in lib

- docs/md/parser.md
- docs/parser.html
- lib/generate.js
- test/nearleyc.test.js
This PR aims to remove common naming collisions from the TypeScript code generation for the following reason:
With the current implementation, code like this fails in a weird way:
```
@preprocessor typescript
@{%
import { Lexer } from '../lexer'
const lexer = new Lexer()
%}
@lexer lexer
```
Typescript will  tell us 2 warnings:
1) `TS2440: Import declaration conflicts with local declaration of 'Lexer'.`
2) `TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.`
This is because this code translates to Typescript that lives in the same scope as the boilerplate generation nearley does at the end of the file, which currently contains `export Lexer: Lexer | undefined = ...` - which is hard to understand unless you inspect the entire `grammar.ts` output file …
> Potential TypeScript naming collisions

- docs/grammar.html
- docs/md/grammar.md
As discussed in #97, there are a few postprocessors that are used internally (`joiner`, `arrconcat`, `arrpush`, and `nuller`) but are not accessible from within nearley grammar.
`nuller` was referenced in documentation despite being inaccessible.  This removes that reference so that documentation reflects reality.
Resolves #97
> Remove nuller from documentation

- docs/package-lock.json
- examples/fun-lang.ne
- lib/nearley.js
- package-lock.json
- package.json
- test/parser.test.js
Fixes this issue: https://github.com/kach/nearley/issues/475.
I apologize for the wait in getting this problem fixed. The excessive memory usage happened because the error reporter built all possible state stack arriving at a current expectant state (state that is expecting a certain terminal token). In some cases, the number of possible states is so large that node.js is spending a lot of time simply allocating memory for the stack and array allocations. The fix was to not build all possible state stacks, but rather simply build one of them - this should have been done in the first place, because the error reporter was using only the first stack anyway. I added a test to the test suite to proof this worked as well, which is based on a grammar I am working with in a toy programming …
> Fix excessive memory usage for error reporting

- lib/nearley.js
When keep history is set to false, States should be evacuated from memory after they are no longer needed. However, all completed states are assigned as a right child from other completed states even after their data is extracted, causing a reference chain that prevents them from ever being garbage collected.
See this screen shot of a memory dump after parsing a file with 34K lines:
As you can see, parsing the said file caused a memory increase of ~350Mb, which was only garbage collected when the parser object  went out of scope.
With the suggested fix, the memory increase when parsing the same file was 60Mb. 
Attaching tests and benchmark output in a separate comment as suggested by the contribution guide.
> Fixed states not being garbage collected with keep history set to false

- lib/nearley.js
Currently, if you have recursive rules in your grammar, and you try to parse some input that has a syntax error, `reportError` crashes with `Cannot read property '0' of null`.
It is obviously tricky to report the full trace in this case, but it seems that at least reporting the state where the error occurred is reasonable.
> Bugfix: avoid error while reporting errors with recursive grammars

- examples/token-2.ne
- lib/nearley.js
- test/parser.test.js
This fixes https://github.com/kach/nearley/issues/487.
Also extracted 2 utility functions getSymbolShortDisplay and getSymbolLongDisplay so that the 2 versions of the symbol display functions are close by each other and future authors can see that they are related.
> Fixed handling of custom matchers written as test functions

- bin/nearley-test.js
- bin/nearley-unparse.js
Currently the error for missing arguments is obscure:
```
internal/validators.js:120
throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:120:11)
at Object.resolve (path.js:980:7)
at Object.<anonymous> (/home/ali/projects/oblong/node_modules/nearley/bin/nearley-test.js:23:32)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
at internal/main/run_main_module.js:17:47 …
```
> Throw an error if grammer js file is not provided

- lib/nearley-language-bootstrapped.js
- lib/nearley-language-bootstrapped.ne
This change would allow whitespace to be used between square brackets for macros, for example:
```
macro1[ expression ] -> expression
macro1[ expression {% id %} ]
```
> Allow whitespace between macro brackets

- lib/nearley-language-bootstrapped.js
- lib/nearley-language-bootstrapped.ne
- test/parser.test.js
`moo` requires `lineBreaks` to be `true` for it to count the number of newlines within a token (presumably to save performance for the majority of the lexing within lines).
This change improves the accuracy of error messages for Nearley grammars - see https://github.com/kach/nearley/issues/539
> Add counting lineBreaks in js and btstring

- docs/md/parser.md
Fix typo with missing `e` in `nearly`.
> Fix typo in parser.md

- docs/getting-started.html
- docs/grammar.html
- docs/md/getting-started.md
- docs/md/grammar.md
- docs/md/parser.md
- docs/md/tokenizers.md
- docs/md/tooling.md
- docs/parser.html
- docs/tokenizers.html
- docs/tooling.html
Thanks for making this library!
I found the docs very helpful to learn how to use nearley, but as I went through them, I came across a few discrepancies, which this PR corrects.
- `node --version` `v17.3.0`
- `nearleyc --version` `2.20.1`
Please let me know if any of these changes are ill-scoped, and I can remove them to help merge this PR.
> Fix errors in docs
